name: Deploy
env:
  LINK_BACKEND: "https://api.render.com/deploy/srv-d504o8ruibrs73drnapg?key=C1otVYrkjRQ"
  LINK_FRONTEND: "https://api.render.com/deploy/srv-d504s33uibrs73drplu0?key=Mn88CJx9z6s"
  LINK_ADMIN: "https://api.render.com/deploy/srv-d504ssmr433s73ehd1fg?key=S1Xy9cNgY6I"
on:
  push:
    branches:
      - DeployBranch

jobs:
  # JOB 1: CHECK CHANGES
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      admin: ${{ steps.filter.outputs.admin }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            admin:
              - 'admin/**'

  # JOB 2: DEPLOY BACKEND
  deploy-backend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deploy
        run: curl "${{ env.LINK_BACKEND }}"

  # JOB 3: DEPLOY FRONTEND
  deploy-frontend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Deploy
        run: curl "${{ env.LINK_FRONTEND }}"

  # JOB 4: DEPLOY ADMIN
  deploy-admin:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.admin == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Admin Deploy
        run: curl "${{ env.LINK_ADMIN }}"