name: Deploy

env:
  LINK_ADMIN: "https://api.render.com/deploy/srv-d504ssmr433s73ehd1fg?key=S1Xy9cNgY6I"
  LINK_FRONTEND: "https://api.render.com/deploy/srv-d504s33uibrs73drplu0?key=Mn88CJx9z6s"
  LINK_BACKEND: "https://api.render.com/deploy/srv-d504o8ruibrs73drnapg?key=C1otVYrkjRQ"

on:
  push:
    branches:
      - DeployBranch
  workflow_dispatch: 

jobs:
  # JOB 1: Xác định thư mục nào có thay đổi
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      admin: ${{ steps.filter.outputs.admin }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'Fast_Food_Delivery/backend/**'
            frontend:
              - 'Fast_Food_Delivery/frontend/**'
            admin:
              - 'Fast_Food_Delivery/admin/**'

  # JOB 2: CHẠY TEST BACKEND (Đây là phần quan trọng nhất cho Tester)
  test-backend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.backend == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Fast_Food_Delivery/backend/package-lock.json

      - name: Install Backend Dependencies
        run: npm install
        working-directory: Fast_Food_Delivery/backend

      - name: Run Backend Tests ✅
        run: npm test # Lệnh này sẽ chạy các Unit Test bạn đã viết
        working-directory: Fast_Food_Delivery/backend

  # JOB 3: DEPLOY BACKEND (Chỉ chạy khi Test PASS)
  deploy-backend:
    needs: [check-changes, test-backend] # Phải vượt qua Job test-backend mới được chạy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deploy
        run: curl "${{ env.LINK_BACKEND }}"

  # JOB 4: DEPLOY FRONTEND
  deploy-frontend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Deploy
        run: curl "${{ env.LINK_FRONTEND }}"

  # JOB 5: DEPLOY ADMIN
  deploy-admin:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.admin == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Admin Deploy
        run: curl "${{ env.LINK_ADMIN }}"
