name: Deploy

env:
  LINK_ADMIN: "https://api.render.com/deploy/srv-d504ssmr433s73ehd1fg?key=S1Xy9cNgY6I"
  LINK_FRONTEND: "https://api.render.com/deploy/srv-d504s33uibrs73drplu0?key=Mn88CJx9z6s"
  LINK_BACKEND: "https://api.render.com/deploy/srv-d504o8ruibrs73drnapg?key=C1otVYrkjRQ"
  STRIPE_SECRET_KEY: "sk_test_dummy" 

on:
  push:
    branches:
      - DeployBranch
  workflow_dispatch: 

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      admin: ${{ steps.filter.outputs.admin }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'Fast_Food_Delivery/backend/**'
            frontend:
              - 'Fast_Food_Delivery/frontend/**'
            admin:
              - 'Fast_Food_Delivery/admin/**'

  # JOB TEST: Tester chú ý - Đây là chốt chặn (Quality Gate)
  test-backend:
    needs: check-changes
    if: ${{ github.event_name == 'workflow_dispatch' || needs.check-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Fast_Food_Delivery/backend/package-lock.json
      - name: Install & Run Test
        run: |
          npm install
          npm test
        working-directory: Fast_Food_Delivery/backend
        env:
          STRIPE_SECRET_KEY: ${{ env.STRIPE_SECRET_KEY }}

  deploy-backend:
    needs: [check-changes, test-backend]
    # Job này không cần IF vì nó phụ thuộc vào test-backend đã có IF rồi
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deploy
        run: curl "${{ env.LINK_BACKEND }}"

  deploy-frontend:
    needs: check-changes
    # SỬA Ở ĐÂY: Thêm ngoặc ${{ }} bao quanh toàn bộ logic
    if: ${{ github.event_name == 'workflow_dispatch' || needs.check-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Deploy
        run: curl "${{ env.LINK_FRONTEND }}"

  deploy-admin:
    needs: check-changes
    # SỬA Ở ĐÂY: Thêm ngoặc ${{ }} bao quanh toàn bộ logic
    if: ${{ github.event_name == 'workflow_dispatch' || needs.check-changes.outputs.admin == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Admin Deploy
        run: curl "${{ env.LINK_ADMIN }}"
